### ISSUE TITLE
Error reading shape from tfrecords

### ISSUE THREAD

**Issue by frankenjoe** [end2you/end2you#2]
Hi,

I ran into the following error when reading 'label_shape' from a tfrecords:

```
Traceback (most recent call last):
  File "..\main.py", line 237, in <module>
    main()
  File "..\main.py", line 234, in main
    e2u.start_process()
  File "..\main.py", line 134, in start_process
    self.data_provider = self.get_data_provider()
  File "..\main.py", line 222, in get_data_provider
    provider(**dp_params)
  File "C:\Users\wagner\Documents\GitHub\end2you\end2you\data_provider\unimodal_provider.py", line 12, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\wagner\Documents\GitHub\end2you\end2you\data_provider\data_provider.py", line 36, in __init__
    self.label_shape = list(self.get_shape(paths[0], 'label_shape'))
  File "C:\Users\wagner\Documents\GitHub\end2you\end2you\data_provider\data_provider.py", line 80, in get_shape
    input_shape = np.fromstring(tt, dtype=np.int64)
ValueError: string size must be a multiple of element size
```

It turned that the value was actually stored as an ``int32``, so changing line 78 in ``data_provider`` from:

```
input_shape = np.fromstring(tt, dtype=np.int64)
```

to 

```
input_shape = np.fromstring(tt, dtype=np.int32)
```

did the trick for me.

Setup: Windows 10, Pyhon 3.5.1, Tensorflow 1.4.0

Thanks for sharing this great library!

**Comment by aliyesilkanat** [comment]
Same in here, did the same trick also
